# This script takes the coverage site matrix generated by GATK depth of coverage and filters samples (both cases and controls) with less than 25 reads on Y-chromosome and less than 50 reads on the X-chromosome and autosomes. It then merges the  samples and then selects sites with atleast 50 reads in 90% of samples 

library(data.table)
library(readr)
library(dplyr)
library(tidyverse)
library(tidyr)

site_matrix_demo <-read.table("/overflow/heinzenlab/dbgap-NABEC/coverage/site_matrix_Xchr1.txt",header=T, sep="\t", stringsAsFactors=F, skip=1)
#controls_matrix<-site_matrix_demo %>%
 #    remove_rownames() %>%
  #   column_to_rownames(var = 'Locus')
controls_matrix_70x_males<-site_matrix_demo%>%
  select(Locus, Depth_for_SH.00.38_combined,
Depth_for_SH.01.31,
Depth_for_SH.03.28_combined,
Depth_for_SH.04.19_combined,
Depth_for_SH.95.21_combined,
Depth_for_UMARY.1104_combined,
Depth_for_UMARY.1259,
Depth_for_UMARY.1274,
Depth_for_UMARY.1277,
Depth_for_UMARY.1441,    
Depth_for_UMARY.1461,
Depth_for_UMARY.1464,          
Depth_for_UMARY.1583_combined,
Depth_for_UMARY.1668_combined,
Depth_for_UMARY.1675,
Depth_for_UMARY.1831,
Depth_for_UMARY.1841,
Depth_for_UMARY.1847_combined,
Depth_for_UMARY.1859,          
Depth_for_UMARY.1861,
Depth_for_UMARY.1866_combined,
Depth_for_UMARY.1935_combined,
Depth_for_UMARY.1936,
Depth_for_UMARY.260,
Depth_for_UMARY.290,
Depth_for_UMARY.4549_combined,
Depth_for_UMARY.4590_combined,
Depth_for_UMARY.4598_combined,
Depth_for_UMARY.4781,        
Depth_for_UMARY.5087_combined, 
Depth_for_UMARY.5088,          
Depth_for_UMARY.5089_combined,
Depth_for_UMARY.5114,          
Depth_for_UMARY.5116,             
Depth_for_UMARY.5123,  
Depth_for_UMARY.5179,
Depth_for_1465_1024.pfc.bulk,
`Depth_for_UMB1024.pfc.1b12`,
`Depth_for_UMB1474.pfc.1b123`,
`Depth_for_UMB1712.pfc.1b12`,
`Depth_for_UMB4672.pfc.1b12_200x`,
`Depth_for_UMB4842.pfc.1b1`,
`Depth_for_UMB5238.pfc.1b123`,
`Depth_for_UMB5391.pfc.1b12`,
`Depth_for_UMB818.pfc.1b1`,
`Depth_for_UMB914.pfc.1b12`)


controls_matrix_70x_females<-site_matrix_demo%>%
  select(Locus, Depth_for_SH.01.37_combined,
Depth_for_SH.02.06_combined,
Depth_for_SH.04.05_combined,
Depth_for_UMARY.1209_combined,
Depth_for_UMARY.1379,
Depth_for_UMARY.1455,
Depth_for_UMARY.1539, 
Depth_for_UMARY.1710_combined,
Depth_for_UMARY.4640_combined,
Depth_for_UMARY.4976,
Depth_for_UMARY.5120,
Depth_for_UMARY.794_combined,
`Depth_for_UMB1499.pfc.1b1`,
`Depth_for_UMB4548.pfc.1b1`,
`Depth_for_UMB5161.pfc.1b1`,
Depth_for_4638_1024.pfc.bulk,
Depth_for_4643_1024.pfc.bulk)

controls_colnames_males<-c("Depth_for_SH.00.38_combined",
"Depth_for_SH.01.31",
"Depth_for_SH.03.28_combined",
"Depth_for_SH.04.19_combined",
"Depth_for_SH.95.21_combined",
"Depth_for_UMARY.1104_combined",
"Depth_for_UMARY.1259",
"Depth_for_UMARY.1274",
"Depth_for_UMARY.1277",
"Depth_for_UMARY.1441",    
"Depth_for_UMARY.1461",
"Depth_for_UMARY.1464",          
"Depth_for_UMARY.1583_combined",
"Depth_for_UMARY.1668_combined",
"Depth_for_UMARY.1675",
"Depth_for_UMARY.1831",
"Depth_for_UMARY.1841",
"Depth_for_UMARY.1847_combined",
"Depth_for_UMARY.1859",          
"Depth_for_UMARY.1861",
"Depth_for_UMARY.1866_combined",
"Depth_for_UMARY.1935_combined",
"Depth_for_UMARY.1936",
"Depth_for_UMARY.260",
"Depth_for_UMARY.290",
"Depth_for_UMARY.4549_combined",
"Depth_for_UMARY.4590_combined",
"Depth_for_UMARY.4598_combined",
"Depth_for_UMARY.4781",          
"Depth_for_UMARY.5087_combined", 
"Depth_for_UMARY.5088",          
"Depth_for_UMARY.5089_combined",
"Depth_for_UMARY.5114",          
"Depth_for_UMARY.5116",             
"Depth_for_UMARY.5123",  
"Depth_for_UMARY.5179",
"Depth_for_1465_1024.pfc.bulk",
"Depth_for_UMB1024.pfc.1b12",
"Depth_for_UMB1474.pfc.1b123",
"Depth_for_UMB1712.pfc.1b12",
"Depth_for_UMB4672.pfc.1b12_200x",
"Depth_for_UMB4842.pfc.1b1",
"Depth_for_UMB5238.pfc.1b123",
"Depth_for_UMB5391.pfc.1b12",
"Depth_for_UMB818.pfc.1b1",
"Depth_for_UMB914.pfc.1b12")

controls_colnames_females<-c("Depth_for_SH.01.37_combined",
"Depth_for_SH.02.06_combined",
"Depth_for_SH.04.05_combined",
"Depth_for_UMARY.1209_combined",
"Depth_for_UMARY.1379",
"Depth_for_UMARY.1455",
"Depth_for_UMARY.1539", 
"Depth_for_UMARY.1710_combined",
"Depth_for_UMARY.4640_combined",
"Depth_for_UMARY.4976",
"Depth_for_UMARY.5120",
"Depth_for_UMARY.794_combined",
"Depth_for_UMB1499.pfc.1b1",
"Depth_for_UMB4548.pfc.1b1",
"Depth_for_UMB5161.pfc.1b1",
"Depth_for_4638_1024.pfc.bulk",
"Depth_for_4643_1024.pfc.bulk")

cases_matrix_70x<-site_matrix_demo%>%
select(Locus,Depth_for_COLE120BR,Depth_for_COLE122BR,Depth_for_COLE131BR,Depth_for_COLE133BR,Depth_for_COLE138BR,Depth_for_COLE139BR,
Depth_for_COLE141BR,Depth_for_COLE153BR,Depth_for_COLE155BR,Depth_for_COLE157BR,Depth_for_COLE159BR,Depth_for_COLE160BR,Depth_for_dukeepi2213br,Depth_for_dukeepi2488br,Depth_for_dukeepi2645br,Depth_for_dukeepi2807br,Depth_for_dukeepi2944br,Depth_for_dukeepi3066br,,Depth_for_UTH0018BR,Depth_for_UTH0019BR,Depth_for_uth0020br,Depth_for_uth0021br,Depth_for_UTH0023BR,Depth_for_UTH0024BR,Depth_for_UTH0026BR,Depth_for_UTH0027BR,Depth_for_UTH0028BR)

cases_colnames<-c("Depth_for_COLE120BR","Depth_for_COLE122BR","Depth_for_COLE131BR","Depth_for_COLE133BR","Depth_for_COLE138BR","Depth_for_COLE139BR","Depth_for_COLE141BR","Depth_for_COLE153BR","Depth_for_COLE155BR","Depth_for_uth0015br","Depth_for_uth0016br","Depth_for_uth0017br","Depth_for_UTH0018BR","Depth_for_UTH0019BR","Depth_for_uth0021br","Depth_for_UTH0023BR","Depth_for_UTH0024BR","Depth_for_UTH0026BR","Depth_for_UTH0028BR")


#write_tsv(controls_matrix_70x_females,"/overflow/heinzenlab/dbgap-NABEC/coverage/coverage_normalized_control_matrix_no_index_females_prefilter")

#for sex chromosomes: males 
is.na(controls_matrix_70x_males[controls_colnames_males]) <-  controls_matrix_70x_males[controls_colnames_males] < 25
#controls_matrix_70x_males<-controls_matrix_70x_males[which(rowMeans(!is.na(controls_matrix_70x_males)) > 0.9), ]

#for sex chromosomes: females 
is.na(controls_matrix_70x_females[controls_colnames_females]) <-  controls_matrix_70x_females[controls_colnames_females] < 50
#controls_matrix_70x_females<-controls_matrix_70x_females[which(rowMeans(!is.na(controls_matrix_70x_females)) > 0.55), ]


write_tsv(controls_matrix_70x_males,"/overflow/heinzenlab/dbgap-NABEC/coverage/coverage_normalized_control_matrix_no_index_males")
write_tsv(controls_matrix_70x_females,"/overflow/heinzenlab/dbgap-NABEC/coverage/coverage_normalized_control_matrix_no_index_females")


#controls_matrix_70x<-merge(controls_matrix_70x_males,controls_matrix_70x_females, by=`Locus`)
controls_matrix_70x<-cbind(controls_matrix_70x_males,controls_matrix_70x_females)
#controls_matrix_70x<-controls_matrix_70x[which(rowMeans(!is.na(controls_matrix_70x)) > 0.90), ]


#write_tsv(controls_matrix_70x_males,"/overflow/heinzenlab/dbgap-NABEC/coverage/coverage_normalized_control_matrix_no_index_males")
write_tsv(controls_matrix_70x,"/overflow/heinzenlab/dbgap-NABEC/coverage/coverage_normalized_50-25x_combined")
q()


# for autosomes 

is.na(cases_matrix_70x[cases_colnames]) <-  cases_matrix_70x[cases_colnames] < 50
cases_matrix_70x<-cases_matrix_70x[which(rowMeans(!is.na(cases_matrix_70x)) > 0.9), ]
write_tsv(cases_matrix_70x,"/proj/heinzenlab/projects/somaticNov2020/coverage/coverage_normalized_case_matrix_no_index")
