#!/bin/bash

	#SBATCH -N 1
	#SBATCH -n 6
	#SBATCH -p general
	#SBATCH --nice=30 
	#SBATCH -t 07-00:00:00
#SBATCH --mem=80g


module add samtools 
module add biobambam2
module add bbmap
module add bwa/0.7.15
module add java
module add picard
module add gatk/4.1.7.0

gatk --java-options "-Xmx40g -Xms40g" GatherVcfs -I  vcf_file_list.txt -O joint_genotypye_output.vcf
