#! /usr/bin/env Rscript
library(readr)
library(dplyr)
library(tidyr)
library(fs)
library(stringr)
data_path <- "/proj/heinzenlab/users/meethila1/controls/"
samples=c("1465_1024-pfc-bulk","4643_1024-pfc-bulk","UMB1024-pfc-1b12","UMB1474-pfc-1b123","UMB1499-pfc-1b1","UMB1712-pfc-1b12","UMB4548-pfc-1b1","UMB5161-pfc-1b1","UMB5238-pfc-1b123","UMB5391-pfc-1b12","UMB818-pfc-1b1","UMB914-pfc-1b12")
for (f in samples) {
Infile_table = paste("/proj/heinzenlab/users/meethila1/controls/",f,"_filtered.vcf.table", sep="")
Infile_bed = paste("/proj/heinzenlab/users/meethila1/controls/", f, "_filtered.vcf.bed", sep="")
Infile_annotated = paste("/proj/heinzenlab/users/meethila1/controls/", f, "_filtered.vcf.annotated.hg38_multianno.txt", sep="")
Outfile=paste("/proj/heinzenlab/users/meethila1/controls/", f, "_final_output.txt", sep="")
Macro1 <- read_tsv(Infile_table)
Macro2 <- read_tsv(Infile_bed)
Macro3 <- read_tsv(Infile_annotated)
vcf_bed_merged<- merge(Macro1, Macro2, by= 'ID', all.x=TRUE)
hg38_DDG2P_15_11_2020 <- read_tsv("/proj/heinzenlab/users/meethila1/humandb/hg38_DDG2P_15_11_2020.txt")
hg38_gnomad_lof_metrics <- read_tsv("/proj/heinzenlab/users/meethila1/humandb/hg38_gnomad_lof_metrics.txt")
hg38_LoFtool_scores <- read_tsv("/proj/heinzenlab/users/meethila1/humandb/hg38_LoFtool_scores.txt")
annnoout1<-merge(Macro3, hg38_LoFtool_scores, by= 'Gene.refGene', all.x = TRUE)
annnoout2<-merge(annnoout1, hg38_DDG2P_15_11_2020, by= 'Gene.refGene', all.x = TRUE)
annnoout3<-merge(annnoout2, hg38_gnomad_lof_metrics, by= 'Gene.refGene', all.x = TRUE)
head(annnoout3)
annnoout3<-annnoout3%>% rename('ID'=`Otherinfo6`)
final_out<-merge(annnoout3,vcf_bed_merged, by= 'ID', all.x = TRUE)
head(final_out)
write_tsv(final_out, Outfile)
}
q()
